// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttuhK9doBQCOrHDn4z_AYDv3Wv-R-dm8',
    appId: '1:371948050582:web:4c4e2c8585a6482ac80ab7',
    messagingSenderId: '371948050582',
    projectId: 'bayti-app-121bd',
    authDomain: 'bayti-app-121bd.firebaseapp.com',
    storageBucket: 'bayti-app-121bd.appspot.com',
    measurementId: 'G-GFBLK5DPWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPaQKsEX-3ABXwCJK1O3joPOx9i9EhJC0',
    appId: '1:371948050582:android:1357471a91d25acdc80ab7',
    messagingSenderId: '371948050582',
    projectId: 'bayti-app-121bd',
    storageBucket: 'bayti-app-121bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9IvL7mm7QGlphkmSH8qLey_SdaxRYihc',
    appId: '1:371948050582:ios:95b873305e5c6ddfc80ab7',
    messagingSenderId: '371948050582',
    projectId: 'bayti-app-121bd',
    storageBucket: 'bayti-app-121bd.appspot.com',
    iosBundleId: 'com.example.batiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9IvL7mm7QGlphkmSH8qLey_SdaxRYihc',
    appId: '1:371948050582:ios:a5e6f3ed34ab9b7fc80ab7',
    messagingSenderId: '371948050582',
    projectId: 'bayti-app-121bd',
    storageBucket: 'bayti-app-121bd.appspot.com',
    iosBundleId: 'com.example.batiApp.RunnerTests',
  );
}
